Feature/social auth
BinaryStudioAcademy/bsa-2018-hedonist pull request #305
Opened 2018-08-21 14:51 UTC by klesogor

This branch contains backend and simple frontend for social auth. This branch should not be merged immediatly, since it has INVALID DOCKER FILES. After your review I will fix remarks and replace docker files with correct ones from development branch.

2018-08-21 16:28 UTC, klesogor commented
Don't forget to register your facebook app and add variables to .env file

2018-08-22 09:01 UTC, nemoipaha requested changes

2018-08-22 09:41 UTC, klesogor commented on app/Actions/SocialAuth/SocialAuthorizeAction.php
> +        } catch (\InvalidArgumentException $exception) {
Socialite itself

2018-08-22 15:08 UTC, klesogor commented on app/Repositories/User/UserRepository.php
> +            function ($query) use ($provider, $token) {
why do we need to type hint framework stuff?

2018-08-22 22:20 UTC, closed without merging